USE [master]
GO

/****** Object:  Database [PersonaBD]    Script Date: 9/07/2021 12:29:56 p. m. ******/
CREATE DATABASE [PersonaBD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PersonaBD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PersonaBD.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PersonaBD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PersonaBD_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PersonaBD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PersonaBD] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PersonaBD] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PersonaBD] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PersonaBD] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PersonaBD] SET ARITHABORT OFF 
GO

ALTER DATABASE [PersonaBD] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [PersonaBD] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PersonaBD] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PersonaBD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PersonaBD] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PersonaBD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PersonaBD] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PersonaBD] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PersonaBD] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PersonaBD] SET  ENABLE_BROKER 
GO

ALTER DATABASE [PersonaBD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PersonaBD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PersonaBD] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PersonaBD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PersonaBD] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PersonaBD] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PersonaBD] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PersonaBD] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PersonaBD] SET  MULTI_USER 
GO

ALTER DATABASE [PersonaBD] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PersonaBD] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PersonaBD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PersonaBD] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PersonaBD] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PersonaBD] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PersonaBD] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PersonaBD] SET  READ_WRITE 
GO


